---
# file: prep.yml
# Playbook to prep OpenShift Enterprise hosts for installation. Run this before
# the openshift-ansible byo playbook.
- name: upgrade all packages before install
  yum: name=* state=latest
- name: Install Basic Preqes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
#    - atomic-openshift-utils
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - httpd-tools
    - docker
    - vim
- name: upgrade all packages
  yum: name=* state=latest
- name: OpenShift use nfs files
  seboolean:
    name: virt_use_nfs
    state: no
    persistent: yes
- name: Remove swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+swap\s+swap'
    state: absent
  notify: disable swap
- name: upgrade all packages in prereqs
  yum: name=* state=latest
    ##### Start Hack to determin storage device #####
- shell: findmnt -no SOURCE
  register: sdccheck
- debug: msg="The /dev/sdc is already in use. This is because microsoft has the /mnt/resource temp directory  which ordinarly should be using the device /dev/sdb sometimes can be mounted under  /dev/sdc  "
  when: sdccheck.stdout.find('sdc') != -1
- set_fact:
    docker_storage_device: "/dev/sdb"
  when: sdccheck.stdout.find('sdc') != -1
- debug: msg="Ok new device set, docker_storage_device={{docker_storage_device}}"
    ##### End Hack to determin storage device #####

- name: creating new LVM volume group
  lvg: vg={{ create_vgname }} pvs={{ docker_storage_device }} state=present
