
# ## https://access.redhat.com/documentation/en/red-hat-mobile-application-platform/4.2/single/core-administration-and-installation-guide/
### Creating PVS entries for RHMAP on premise deployments
### The expectation is the nfs server has these entries already
- hosts: localhost
  connection: localhost
  roles:
    - { role: storagedisk }
- hosts: gatewayed-masters:gatewayed-nodes
  strategy: free
  serial: 3
  vars:
    publicjumpdns: "{{ hostvars['localhost']['publicjumpdns']}}"
    publicjumpip: "{{ hostvars['localhost']['publicjumpip']}}"
    routerpublicip: "{{ hostvars['localhost']['routerpublicip']}}"
    ansible_ssh_common_args: -o ProxyCommand="ssh -W %h:%p -q {{ adminUsername }}@{{ publicjumpip }}"

  gather_facts: false
  user: "{{ adminUsername }}"
  sudo: true
  roles:
    - { role: gluster_subscribe }
- hosts: gatewayed-nodes
  strategy: free
  vars:
    publicjumpdns: "{{ hostvars['localhost']['publicjumpdns']}}"
    publicjumpip: "{{ hostvars['localhost']['publicjumpip']}}"
    routerpublicip: "{{ hostvars['localhost']['routerpublicip']}}"
    ansible_ssh_common_args: -o ProxyCommand="ssh -W %h:%p -q {{ adminUsername }}@{{ publicjumpip }}"

  gather_facts: false
  user: "{{ adminUsername }}"
  sudo: true
  roles:
    - { role: gluster_prereqs_client }

- hosts: gatewayed-storage
  strategy: free
  vars:
    publicjumpdns: "{{ hostvars['localhost']['publicjumpdns']}}"
    publicjumpip: "{{ hostvars['localhost']['publicjumpip']}}"
    routerpublicip: "{{ hostvars['localhost']['routerpublicip']}}"
    ansible_ssh_common_args: -o ProxyCommand="ssh -W %h:%p -q {{ adminUsername }}@{{ publicjumpip }}"
  gather_facts: false
  user: "{{ adminUsername }}"
  sudo: true
  roles:
    - { role: gluster_prereqs_node }

- hosts: gatewayed-masters[0]
  strategy: free
  vars:
    publicjumpdns: "{{ hostvars['localhost']['publicjumpdns']}}"
    publicjumpip: "{{ hostvars['localhost']['publicjumpip']}}"
    routerpublicip: "{{ hostvars['localhost']['routerpublicip']}}"
    ansible_ssh_common_args: -o ProxyCommand="ssh -W %h:%p -q {{ adminUsername }}@{{ publicjumpip }}"

  gather_facts: false
  user: "{{ adminUsername }}"
  sudo: true
  roles:
    - { role: gluster_prereqs_deploy }
    - { role: gluster_install}
