---
- hosts: localhost
  connection: local
  name: Sanity check
  gather_facts: no
  vars:
    mastercount: "{{ masters | length }}"
    storagecount: "{{ storage | default([]) | length }}"
  tasks:
    - debug: msg="Checking if master size is correct either 1,3 or 5. Current size={{ mastercount }} "
    - name: 'check parm is null or invalid'
      fail: msg="Openshift installation supports either 1, 3, or 5 masters because of etcd's qourm. Your corrent number of masters is \"{{ masters | length }}\". Please ensure your master size fulfills this requirement. Update the dict/array called masters in the file groups/all"
      when:
        - mastercount  != '1'
        - mastercount  != '3'
        - mastercount  != '5'
    - debug: msg="Checking if storage size is correct either 3, 5, 7. Current size={{ storagecount }} "
      when:
      - install_storage is defined
      - install_storage
    - name: 'check parm is null or invalid'
      fail: msg="Openshift installation supports either 3, 5, 7 storage nodes because of storage's qourm. Your corrent number of storage is \"{{ storage | length }}\". Please ensure your master size fulfills this requirement. Update the dict/array called storage in the file groups/all"
      when:
      - storagecount  != '3'
      - storagecount  != '5'
      - storagecount  != '7'
      - install_storage is defined
      - install_storage

- include: provision_infrastructure.yml
- include: perform_prereqs_origin.yml
  when:
  - openshiftorigin is defined
  - openshiftorigin
- include: perform_prereqs.yml
  when:
  - openshiftorigin is defined
  - not openshiftorigin
- include: install_openshift.yml
- include: metrics.yml
- include: logging.yml
- include: restart.yml
- include: configure_gluster.yml
  when:
  - install_storage is defined
  - install_storage
- include: configure_rhnmapstorage.yml
  when:
  - install_rhmap is defined
  - install_rhmap
- include: configure.rhmap.yaml
  when:
  - install_rhmap is defined
  - install_rhmap
- include: configure_sso.yaml
  when:
  - install_sso is defined
  - install_sso
- hosts: localhost
  connection: local
  name: Success message
  tasks:
    - debug: msg="Congrats. Openshift should be now up and running under https://{{ publicjumpdns }}:443/"
    - debug: msg="You can login using your user {{ adminUsername }}@{{ publicjumpip }}"
    - debug: msg="You will need to configure your dns to talk to the openshift router under  {{ routerpublicip }}"
  handlers:
    - name: Get Ansible log files
      fetch:
        src: /tmp/ansible.log
        dest: "{{ resource_group_name }}_ansible.log"
        flat: yes
